# Deterministic reference only; generated by M106-001.
from tools.audit_sequence_paired_revolve import build_shape, load_json, write_step

entry = load_json('case.json')
write_step(build_shape(entry), 'output/model.step')
