# Deterministic reference only; generated by M106-001 and sandbox self-contained.
import math

from OCP.BRepBuilderAPI import BRepBuilderAPI_MakeFace, BRepBuilderAPI_MakePolygon
from OCP.BRepPrimAPI import BRepPrimAPI_MakeRevol
from OCP.gp import gp_Ax1, gp_Dir, gp_Pnt
from OCP.STEPControl import STEPControl_AsIs, STEPControl_Writer

p = {"axis_x": 0.0, "z_min": 0.0, "inner_radius": 6.0, "lower_outer_radius": 18.0, "upper_outer_radius": 12.0, "lower_height": 16.0, "upper_height": 28.0}
x, z = p["axis_x"], p["z_min"]
wire = BRepBuilderAPI_MakePolygon()
for px, pz in ((x + p["inner_radius"], z), (x + p["lower_outer_radius"], z), (x + p["lower_outer_radius"], p["lower_height"]), (x + p["upper_outer_radius"], p["lower_height"]), (x + p["upper_outer_radius"], p["upper_height"]), (x + p["inner_radius"], p["upper_height"])):
    wire.Add(gp_Pnt(px, 0.0, pz))
wire.Close()
shape = BRepPrimAPI_MakeRevol(BRepBuilderAPI_MakeFace(wire.Wire()).Face(), gp_Ax1(gp_Pnt(x, 0.0, z), gp_Dir(0, 0, 1)), 2.0 * math.pi).Shape()
writer = STEPControl_Writer()
writer.Transfer(shape, STEPControl_AsIs)
writer.Write("output/model.step")
