# Deterministic reference only; generated by M90-002.
from OCP.BRepAlgoAPI import BRepAlgoAPI_Cut
from OCP.BRepPrimAPI import BRepPrimAPI_MakeBox, BRepPrimAPI_MakeCylinder
from OCP.gp import gp_Ax2, gp_Dir, gp_Pnt
from OCP.STEPControl import STEPControl_Writer, STEPControl_AsIs

p = {
    "base_length_x": 56.0,
    "base_length_y": 44.0,
    "base_height": 14.0,
    "grid_center_xy": [23.0, 17.0],
    "x_spacing": 18.0,
    "y_spacing": 14.0,
    "hole_radius": 3.0,
}
base = BRepPrimAPI_MakeBox(p["base_length_x"], p["base_length_y"], p["base_height"]).Shape()
shape = base
cx, cy = p["grid_center_xy"]
for dx in (-1.0, 1.0):
    for dy in (-1.0, 1.0):
        cutter = BRepPrimAPI_MakeCylinder(
            gp_Ax2(
                gp_Pnt(cx + dx * p["x_spacing"] / 2, cy + dy * p["y_spacing"] / 2, -1),
                gp_Dir(0, 0, 1),
            ),
            p["hole_radius"],
            p["base_height"] + 2,
        ).Shape()
        shape = BRepAlgoAPI_Cut(shape, cutter).Shape()
writer = STEPControl_Writer()
writer.Transfer(shape, STEPControl_AsIs)
writer.Write("output/model.step")
