"""Build only M130's six frozen shell candidates offline."""

from __future__ import annotations
import hashlib
import json
import tempfile
from pathlib import Path
from brep2code.brep.probes import load_model, probe_summary

try:
    from tools.audit_sequence_paired_shell import (
        EXPANSION,
        ROOT,
        build_shape,
        canonical_sequence,
        load_json,
        write_step,
    )
    from tools.build_m20_counterbore_candidates import normalize_step_header
except ModuleNotFoundError:  # pragma: no cover
    from audit_sequence_paired_shell import (
        EXPANSION,
        ROOT,
        build_shape,
        canonical_sequence,
        load_json,
        write_step,
    )
    from build_m20_counterbore_candidates import normalize_step_header


def _write(e, p):
    write_step(build_shape(e), p)
    normalize_step_header(p)
    return hashlib.sha256(p.read_bytes()).hexdigest()


def build():
    r = load_json(EXPANSION)
    rows = r["cases"]
    if len(rows) != 6:
        raise ValueError("M131 production requires six frozen rows")
    made = []
    for e in rows:
        with tempfile.TemporaryDirectory() as a, tempfile.TemporaryDirectory() as b:
            x, y = Path(a) / "m.step", Path(b) / "m.step"
            if _write(e, x) != _write(e, y) or x.read_bytes() != y.read_bytes():
                raise RuntimeError(f"hash nondeterminism: {e['case_id']}")
        d = ROOT / e["candidate_directory"]
        d.mkdir(parents=True, exist_ok=True)
        target = d / "input.step"
        digest = _write(e, target)
        seq = canonical_sequence(e)
        meta = {
            "case_id": e["case_id"],
            "status": "experimental",
            "origin": "self_authored",
            "tier": "P2",
            "fixture_version": 1,
            "family_id": e["family_id"],
            "data_split": e["data_split"],
            "variant": e["variant"],
            "parameters": e["parameters"],
            "input_step": "input.step",
            "reference_script_status": "available",
            "reference_script": "reference_build_sequence.py",
            "sha256": digest,
            "unit": "mm",
            "expected": probe_summary(load_model(target)),
            "sequence_pair": {
                "grammar_version": r["grammar_version"],
                "oracle_provenance": r["oracle_provenance"],
                "sequence": seq,
                "candidate_sequence": "candidate_sequence.json",
            },
            "admission_boundary": "Experimental candidate only; absent from registry, manifest, provider, training, and runtime paths.",
        }
        (d / "candidate_sequence.json").write_text(
            json.dumps({"grammar_version": r["grammar_version"], "sequence": seq}, indent=2) + "\n",
            encoding="utf-8",
        )
        (d / "case.json").write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
        (d / "reference_build_sequence.py").write_text(
            "# Deterministic reference only; generated by M131-001.\nfrom tools.audit_sequence_paired_shell import build_shape, load_json, write_step\nentry=load_json('case.json')\nwrite_step(build_shape(entry), 'output/model.step')\n",
            encoding="utf-8",
        )
        made.append(e["case_id"])
    return made


if __name__ == "__main__":
    print(json.dumps({"produced": build(), "status": "experimental_candidates"}, indent=2))
